{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "31b4f421-d931-4e92-ab7e-2149d621da1c",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2025-04-22 12:17:23.183 \n",
      "  \u001b[33m\u001b[1mWarning:\u001b[0m to view this Streamlit app on a browser, run it with the following\n",
      "  command:\n",
      "\n",
      "    streamlit run C:\\Users\\khush\\AppData\\Roaming\\Python\\Python312\\site-packages\\ipykernel_launcher.py [ARGUMENTS]\n"
     ]
    },
    {
     "ename": "RuntimeError",
     "evalue": "Runtime hasn't been created!",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mFileNotFoundError\u001b[0m                         Traceback (most recent call last)",
      "File \u001b[1;32m~\\anaconda3\\Lib\\site-packages\\streamlit\\elements\\image.py:381\u001b[0m, in \u001b[0;36mimage_to_url\u001b[1;34m(image, width, clamp, channels, output_format, image_id)\u001b[0m\n\u001b[0;32m    380\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m--> 381\u001b[0m     \u001b[38;5;28;01mwith\u001b[39;00m \u001b[38;5;28;43mopen\u001b[39;49m\u001b[43m(\u001b[49m\u001b[43mimage\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43mrb\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m)\u001b[49m \u001b[38;5;28;01mas\u001b[39;00m f:\n\u001b[0;32m    382\u001b[0m         image_data \u001b[38;5;241m=\u001b[39m f\u001b[38;5;241m.\u001b[39mread()\n",
      "\u001b[1;31mFileNotFoundError\u001b[0m: [Errno 2] No such file or directory: 'images/logo.png'",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[1;31mRuntimeError\u001b[0m                              Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[1], line 203\u001b[0m\n\u001b[0;32m    199\u001b[0m             visualize_speech()\n\u001b[0;32m    202\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;18m__name__\u001b[39m \u001b[38;5;241m==\u001b[39m \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124m__main__\u001b[39m\u001b[38;5;124m\"\u001b[39m:\n\u001b[1;32m--> 203\u001b[0m     \u001b[43mmain\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n",
      "Cell \u001b[1;32mIn[1], line 126\u001b[0m, in \u001b[0;36mmain\u001b[1;34m()\u001b[0m\n\u001b[0;32m    123\u001b[0m     st\u001b[38;5;241m.\u001b[39mwrite(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124m\"\u001b[39m)\n\u001b[0;32m    125\u001b[0m \u001b[38;5;28;01mwith\u001b[39;00m col2:\n\u001b[1;32m--> 126\u001b[0m     \u001b[43mst\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mimage\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43mimages/logo.png\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43muse_column_width\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;28;43;01mTrue\u001b[39;49;00m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mcaption\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43mGenerated by DALL-E\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m)\u001b[49m\n\u001b[0;32m    128\u001b[0m \u001b[38;5;28;01mwith\u001b[39;00m col3:\n\u001b[0;32m    129\u001b[0m     st\u001b[38;5;241m.\u001b[39mwrite(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124m\"\u001b[39m)\n",
      "File \u001b[1;32m~\\anaconda3\\Lib\\site-packages\\streamlit\\runtime\\metrics_util.py:397\u001b[0m, in \u001b[0;36mgather_metrics.<locals>.wrapped_func\u001b[1;34m(*args, **kwargs)\u001b[0m\n\u001b[0;32m    395\u001b[0m         _LOGGER\u001b[38;5;241m.\u001b[39mdebug(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mFailed to collect command telemetry\u001b[39m\u001b[38;5;124m\"\u001b[39m, exc_info\u001b[38;5;241m=\u001b[39mex)\n\u001b[0;32m    396\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m--> 397\u001b[0m     result \u001b[38;5;241m=\u001b[39m \u001b[43mnon_optional_func\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[43margs\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[43mkwargs\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m    398\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m RerunException \u001b[38;5;28;01mas\u001b[39;00m ex:\n\u001b[0;32m    399\u001b[0m     \u001b[38;5;66;03m# Duplicated from below, because static analysis tools get confused\u001b[39;00m\n\u001b[0;32m    400\u001b[0m     \u001b[38;5;66;03m# by deferring the rethrow.\u001b[39;00m\n\u001b[0;32m    401\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m tracking_activated \u001b[38;5;129;01mand\u001b[39;00m command_telemetry:\n",
      "File \u001b[1;32m~\\anaconda3\\Lib\\site-packages\\streamlit\\elements\\image.py:161\u001b[0m, in \u001b[0;36mImageMixin.image\u001b[1;34m(self, image, caption, width, use_column_width, clamp, channels, output_format)\u001b[0m\n\u001b[0;32m    158\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m StreamlitAPIException(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mImage width must be positive.\u001b[39m\u001b[38;5;124m\"\u001b[39m)\n\u001b[0;32m    160\u001b[0m image_list_proto \u001b[38;5;241m=\u001b[39m ImageListProto()\n\u001b[1;32m--> 161\u001b[0m \u001b[43mmarshall_images\u001b[49m\u001b[43m(\u001b[49m\n\u001b[0;32m    162\u001b[0m \u001b[43m    \u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mdg\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_get_delta_path_str\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m    163\u001b[0m \u001b[43m    \u001b[49m\u001b[43mimage\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m    164\u001b[0m \u001b[43m    \u001b[49m\u001b[43mcaption\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m    165\u001b[0m \u001b[43m    \u001b[49m\u001b[43mwidth\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m    166\u001b[0m \u001b[43m    \u001b[49m\u001b[43mimage_list_proto\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m    167\u001b[0m \u001b[43m    \u001b[49m\u001b[43mclamp\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m    168\u001b[0m \u001b[43m    \u001b[49m\u001b[43mchannels\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m    169\u001b[0m \u001b[43m    \u001b[49m\u001b[43moutput_format\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m    170\u001b[0m \u001b[43m\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m    171\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mdg\u001b[38;5;241m.\u001b[39m_enqueue(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mimgs\u001b[39m\u001b[38;5;124m\"\u001b[39m, image_list_proto)\n",
      "File \u001b[1;32m~\\anaconda3\\Lib\\site-packages\\streamlit\\elements\\image.py:544\u001b[0m, in \u001b[0;36mmarshall_images\u001b[1;34m(coordinates, image, caption, width, proto_imgs, clamp, channels, output_format)\u001b[0m\n\u001b[0;32m    540\u001b[0m \u001b[38;5;66;03m# We use the index of the image in the input image list to identify this image inside\u001b[39;00m\n\u001b[0;32m    541\u001b[0m \u001b[38;5;66;03m# MediaFileManager. For this, we just add the index to the image's \"coordinates\".\u001b[39;00m\n\u001b[0;32m    542\u001b[0m image_id \u001b[38;5;241m=\u001b[39m \u001b[38;5;124m\"\u001b[39m\u001b[38;5;132;01m%s\u001b[39;00m\u001b[38;5;124m-\u001b[39m\u001b[38;5;132;01m%i\u001b[39;00m\u001b[38;5;124m\"\u001b[39m \u001b[38;5;241m%\u001b[39m (coordinates, coord_suffix)\n\u001b[1;32m--> 544\u001b[0m proto_img\u001b[38;5;241m.\u001b[39murl \u001b[38;5;241m=\u001b[39m \u001b[43mimage_to_url\u001b[49m\u001b[43m(\u001b[49m\n\u001b[0;32m    545\u001b[0m \u001b[43m    \u001b[49m\u001b[43mimage\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mwidth\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mclamp\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mchannels\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43moutput_format\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mimage_id\u001b[49m\n\u001b[0;32m    546\u001b[0m \u001b[43m\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[1;32m~\\anaconda3\\Lib\\site-packages\\streamlit\\elements\\image.py:393\u001b[0m, in \u001b[0;36mimage_to_url\u001b[1;34m(image, width, clamp, channels, output_format, image_id)\u001b[0m\n\u001b[0;32m    390\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m mimetype \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n\u001b[0;32m    391\u001b[0m     mimetype \u001b[38;5;241m=\u001b[39m \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mapplication/octet-stream\u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m--> 393\u001b[0m url \u001b[38;5;241m=\u001b[39m \u001b[43mruntime\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mget_instance\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\u001b[38;5;241m.\u001b[39mmedia_file_mgr\u001b[38;5;241m.\u001b[39madd(image, mimetype, image_id)\n\u001b[0;32m    394\u001b[0m caching\u001b[38;5;241m.\u001b[39msave_media_data(image, mimetype, image_id)\n\u001b[0;32m    395\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m url\n",
      "File \u001b[1;32m~\\anaconda3\\Lib\\site-packages\\streamlit\\runtime\\__init__.py:28\u001b[0m, in \u001b[0;36mget_instance\u001b[1;34m()\u001b[0m\n\u001b[0;32m     24\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21mget_instance\u001b[39m() \u001b[38;5;241m-\u001b[39m\u001b[38;5;241m>\u001b[39m Runtime:\n\u001b[0;32m     25\u001b[0m \u001b[38;5;250m    \u001b[39m\u001b[38;5;124;03m\"\"\"Return the singleton Runtime instance. Raise an Error if the\u001b[39;00m\n\u001b[0;32m     26\u001b[0m \u001b[38;5;124;03m    Runtime hasn't been created yet.\u001b[39;00m\n\u001b[0;32m     27\u001b[0m \u001b[38;5;124;03m    \"\"\"\u001b[39;00m\n\u001b[1;32m---> 28\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[43mRuntime\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43minstance\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[1;32m~\\anaconda3\\Lib\\site-packages\\streamlit\\runtime\\runtime.py:150\u001b[0m, in \u001b[0;36mRuntime.instance\u001b[1;34m(cls)\u001b[0m\n\u001b[0;32m    146\u001b[0m \u001b[38;5;250m\u001b[39m\u001b[38;5;124;03m\"\"\"Return the singleton Runtime instance. Raise an Error if the\u001b[39;00m\n\u001b[0;32m    147\u001b[0m \u001b[38;5;124;03mRuntime hasn't been created yet.\u001b[39;00m\n\u001b[0;32m    148\u001b[0m \u001b[38;5;124;03m\"\"\"\u001b[39;00m\n\u001b[0;32m    149\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28mcls\u001b[39m\u001b[38;5;241m.\u001b[39m_instance \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n\u001b[1;32m--> 150\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mRuntimeError\u001b[39;00m(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mRuntime hasn\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mt been created!\u001b[39m\u001b[38;5;124m\"\u001b[39m)\n\u001b[0;32m    151\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28mcls\u001b[39m\u001b[38;5;241m.\u001b[39m_instance\n",
      "\u001b[1;31mRuntimeError\u001b[0m: Runtime hasn't been created!"
     ]
    }
   ],
   "source": [
    "import streamlit as st\n",
    "\n",
    "st.title(\"Hello, Streamlit!\")\n",
    "st.write(\"This is a simple Streamlit app running from Jupyter.\")\n",
    "import streamlit as st\n",
    "import requests\n",
    "from PIL import Image\n",
    "from transformers import BlipProcessor, BlipForConditionalGeneration, SpeechT5Processor, SpeechT5ForTextToSpeech, SpeechT5HifiGan\n",
    "import os\n",
    "import torch\n",
    "import soundfile as sf\n",
    "from datasets import load_dataset\n",
    "import matplotlib.pyplot as plt\n",
    "import numpy as np\n",
    "os.environ['KMP_DUPLICATE_LIB_OK'] = 'True'\n",
    "\n",
    "# Model Description\n",
    "model_description = \"\"\"\n",
    "This application utilizes image captioning and text-to-speech models to generate a caption for an uploaded image \n",
    "and convert the caption into speech.\n",
    "\n",
    "The image captioning model is based on [Salesforce's BLIP architecture](https://huggingface.co/Salesforce/blip-image-captioning-base), which can generate descriptive captions for images.\n",
    "\n",
    "The text-to-speech model, based on [Microsoft's SpeechT5](https://huggingface.co/microsoft/speecht5_tts), converts the generated caption into speech with the help of a \n",
    "HiFiGAN vocoder.\n",
    "\"\"\"\n",
    "\n",
    "\n",
    "@st.cache_resource\n",
    "def initialize_image_captioning():\n",
    "    processor = BlipProcessor.from_pretrained(\"Salesforce/blip-image-captioning-base\")\n",
    "    model = BlipForConditionalGeneration.from_pretrained(\"Salesforce/blip-image-captioning-base\")\n",
    "    return processor, model\n",
    "\n",
    "@st.cache_resource\n",
    "def initialize_speech_synthesis():\n",
    "    processor = SpeechT5Processor.from_pretrained(\"microsoft/speecht5_tts\")\n",
    "    model = SpeechT5ForTextToSpeech.from_pretrained(\"microsoft/speecht5_tts\")\n",
    "    vocoder = SpeechT5HifiGan.from_pretrained(\"microsoft/speecht5_hifigan\")\n",
    "    embeddings_dataset = load_dataset(\"Matthijs/cmu-arctic-xvectors\", split=\"validation\")\n",
    "    speaker_embeddings = torch.tensor(embeddings_dataset[7306][\"xvector\"]).unsqueeze(0)\n",
    "    return processor, model, vocoder, speaker_embeddings\n",
    "\n",
    "def generate_caption(processor, model, image):\n",
    "    inputs = processor(image, return_tensors=\"pt\")\n",
    "    out = model.generate(**inputs)\n",
    "    output_caption = processor.decode(out[0], skip_special_tokens=True)\n",
    "    return output_caption\n",
    "\n",
    "def generate_speech(processor, model, vocoder, speaker_embeddings, caption):\n",
    "    inputs = processor(text=caption, return_tensors=\"pt\")\n",
    "    speech = model.generate_speech(inputs[\"input_ids\"], speaker_embeddings, vocoder=vocoder)\n",
    "    sf.write(\"speech.wav\", speech.numpy(), samplerate=16000)\n",
    "\n",
    "def play_sound():\n",
    "    audio_file = open(\"speech.wav\", 'rb')\n",
    "    audio_bytes = audio_file.read()\n",
    "    st.audio(audio_bytes, format='audio/wav')\n",
    "\n",
    "def visualize_speech():\n",
    "    data, samplerate = sf.read(\"speech.wav\")\n",
    "    duration = len(data) / samplerate\n",
    "\n",
    "    # Create time axis\n",
    "    time = np.linspace(0., duration, len(data))\n",
    "\n",
    "     # Plot the speech waveform\n",
    "    fig, ax = plt.subplots(figsize=(10, 4))\n",
    "    ax.plot(time, data)\n",
    "    ax.set(xlabel=\"Time (s)\", ylabel=\"Amplitude\", title=\"Speech Waveform\")\n",
    "\n",
    "    # Display the plot using st.pyplot()\n",
    "    st.pyplot(fig)\n",
    "\n",
    "def main():\n",
    "    st.set_page_config(\n",
    "    page_title=\"Image-to-Speech\",\n",
    "    page_icon=\"📸\",\n",
    "    initial_sidebar_state=\"collapsed\",\n",
    "    menu_items={\n",
    "        'Get Help': 'https://www.extremelycoolapp.com/help',\n",
    "        'Report a bug': \"https://www.extremelycoolapp.com/bug\",\n",
    "        'About': \"# This is a header. This is an *extremely* cool app!\"\n",
    "    }\n",
    ")\n",
    "\n",
    "    st.sidebar.markdown(\"---\")\n",
    "    st.sidebar.markdown(\"Developed by Alim Tleuliyev\")\n",
    "    st.sidebar.markdown(\"Contact: [alim.tleuliyev@nu.edu.kz](mailto:alim.tleuliyev@nu.edu.kz)\")\n",
    "    st.sidebar.markdown(\"GitHub: [Repo](https://github.com/AlimTleuliyev/image-to-audio)\")\n",
    "\n",
    "    st.markdown(\n",
    "        \"\"\"\n",
    "        <style>\n",
    "        .container {\n",
    "            max-width: 800px;\n",
    "        }\n",
    "        .title {\n",
    "            text-align: center;\n",
    "            font-size: 32px;\n",
    "            font-weight: bold;\n",
    "            margin-bottom: 20px;\n",
    "        }\n",
    "        .description {\n",
    "            margin-bottom: 30px;\n",
    "        }\n",
    "        .instructions {\n",
    "            margin-bottom: 20px;\n",
    "            padding: 10px;\n",
    "            background-color: #f5f5f5;\n",
    "            border-radius: 5px;\n",
    "        }\n",
    "        </style>\n",
    "        \"\"\",\n",
    "        unsafe_allow_html=True\n",
    "    )\n",
    "\n",
    "    # Title\n",
    "    st.markdown(\"<div class='title'>Image Captioning and Text-to-Speech</div>\", unsafe_allow_html=True)\n",
    "    col1, col2, col3 = st.columns([1,2,1])\n",
    "\n",
    "    with col1:\n",
    "        st.write(\"\")\n",
    "\n",
    "    with col2:\n",
    "        st.image(\"images/logo.png\", use_column_width=True, caption=\"Generated by DALL-E\")\n",
    "\n",
    "    with col3:\n",
    "        st.write(\"\")\n",
    "\n",
    "    # Model Description\n",
    "    st.markdown(\"<div class='description'>\" + model_description + \"</div>\", unsafe_allow_html=True)\n",
    "\n",
    "    # Instructions\n",
    "    with st.expander(\"Instructions\"):\n",
    "        st.markdown(\"1. Upload an image or provide the URL of an image.\")\n",
    "        st.markdown(\"2. Click the 'Generate Caption and Speech' button.\")\n",
    "        st.markdown(\"3. The generated caption will be displayed, and the speech will start playing.\")\n",
    "\n",
    "\n",
    "    # Choose image source\n",
    "    image_source = st.radio(\"Select Image Source:\", (\"Upload Image\", \"Open from URL\"))\n",
    "\n",
    "    image = None\n",
    "\n",
    "    if image_source == \"Upload Image\":\n",
    "        # File uploader for image\n",
    "        uploaded_file = st.file_uploader(\"Upload an image\", type=[\"png\", \"jpg\", \"jpeg\"])\n",
    "        if uploaded_file is not None:\n",
    "            image = Image.open(uploaded_file)\n",
    "        else:\n",
    "            image = None\n",
    "\n",
    "    else:\n",
    "        # Input box for image URL\n",
    "        url = st.text_input(\"Enter the image URL:\")\n",
    "        if url:\n",
    "            try:\n",
    "                response = requests.get(url, stream=True)\n",
    "                if response.status_code == 200:\n",
    "                    image = Image.open(response.raw)\n",
    "                else:\n",
    "                    st.error(\"Error loading image from URL.\")\n",
    "                    image = None\n",
    "            except requests.exceptions.RequestException as e:\n",
    "                st.error(f\"Error loading image from URL: {e}\")\n",
    "                image = None\n",
    "\n",
    "    # Generate caption and play sound button\n",
    "    if image is not None:\n",
    "        # Display the uploaded image\n",
    "        st.image(image, caption='Uploaded Image', use_column_width=True)\n",
    "\n",
    "        # Initialize image captioning models\n",
    "        caption_processor, caption_model = initialize_image_captioning()\n",
    "\n",
    "        # Initialize speech synthesis models\n",
    "        speech_processor, speech_model, speech_vocoder, speaker_embeddings = initialize_speech_synthesis()\n",
    "\n",
    "        # Generate caption\n",
    "        with st.spinner(\"Generating Caption...\"):\n",
    "            output_caption = generate_caption(caption_processor, caption_model, image)\n",
    "\n",
    "        # Display the caption\n",
    "        st.subheader(\"Caption:\")\n",
    "        st.write(output_caption)\n",
    "        \n",
    "        # Generate speech from the caption\n",
    "        with st.spinner(\"Generating Speech...\"):\n",
    "            generate_speech(speech_processor, speech_model, speech_vocoder, speaker_embeddings, output_caption)\n",
    "\n",
    "        \n",
    "        st.subheader(\"Audio:\")\n",
    "        # Play the generated sound\n",
    "        play_sound()\n",
    "\n",
    "        # Visualize the speech waveform\n",
    "        with st.expander(\"See visualization\"):\n",
    "            visualize_speech()\n",
    "\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    main()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "ddde8f70-1225-498c-a4ad-80ed36a109d5",
   "metadata": {},
   "outputs": [
    {
     "ename": "SyntaxError",
     "evalue": "incomplete input (2674410274.py, line 16)",
     "output_type": "error",
     "traceback": [
      "\u001b[1;36m  Cell \u001b[1;32mIn[3], line 16\u001b[1;36m\u001b[0m\n\u001b[1;33m    '''\u001b[0m\n\u001b[1;37m    ^\u001b[0m\n\u001b[1;31mSyntaxError\u001b[0m\u001b[1;31m:\u001b[0m incomplete input\n"
     ]
    }
   ],
   "source": [
    "import streamlit as st\n",
    "import os\n",
    "\n",
    "def main():\n",
    "    st.title(\"My Streamlit App\")\n",
    "\n",
    "    image_path = \"images/logo.png\"\n",
    "\n",
    "    if os.path.exists(image_path):\n",
    "        st.image(image_path, use_column_width=True, caption=\"Generated by DALL·E\")\n",
    "    else:\n",
    "        st.warning(f\"Image not found: {image_path}\")\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    main()\n",
    "'''\n",
    "\n",
    "# Save the code to a Python file\n",
    "with open(\"my_app.py\", \"w\") as f:\n",
    "    f.write(code)\n",
    "\n",
    "print(\"✅ File 'my_app.py' created.\")\n",
    "print(\"👉 Now open your terminal and run:\\n   streamlit run my_app.py\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "0889c428-4349-4d6d-84be-06625006f177",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "✅ File 'my_app.py' created.\n",
      "👉 Now open your terminal and run:\n",
      "   streamlit run my_app.py\n"
     ]
    }
   ],
   "source": [
    "# This will create and save a Streamlit app file\n",
    "code = '''import streamlit as st\n",
    "import os\n",
    "\n",
    "def main():\n",
    "    st.title(\"My Streamlit App\")\n",
    "\n",
    "    image_path = \"images/logo.png\"\n",
    "\n",
    "    if os.path.exists(image_path):\n",
    "        st.image(image_path, use_column_width=True, caption=\"Generated by DALL·E\")\n",
    "    else:\n",
    "        st.warning(f\"Image not found: {image_path}\")\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    main()\n",
    "'''\n",
    "\n",
    "# Save the code to a Python file\n",
    "with open(\"my_app.py\", \"w\") as f:\n",
    "    f.write(code)\n",
    "\n",
    "print(\"✅ File 'my_app.py' created.\")\n",
    "print(\"👉 Now open your terminal and run:\\n   streamlit run my_app.py\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "2faffbe7-1185-4772-b0bf-25b3b09087e7",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'C:\\\\Users\\\\khush\\\\Downloads\\\\image-to-audio-master (1)\\\\image-to-audio-master\\\\Untitled Folder'"
      ]
     },
     "execution_count": 7,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import os\n",
    "os.getcwd()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "6fdeb5cf-aede-49e2-a5e0-ebd3e076c6a2",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: streamlit in c:\\users\\khush\\anaconda3\\lib\\site-packages (1.32.0)\n",
      "Requirement already satisfied: altair<6,>=4.0 in c:\\users\\khush\\anaconda3\\lib\\site-packages (from streamlit) (5.0.1)\n",
      "Requirement already satisfied: blinker<2,>=1.0.0 in c:\\users\\khush\\anaconda3\\lib\\site-packages (from streamlit) (1.6.2)\n",
      "Requirement already satisfied: cachetools<6,>=4.0 in c:\\users\\khush\\anaconda3\\lib\\site-packages (from streamlit) (5.3.3)\n",
      "Requirement already satisfied: click<9,>=7.0 in c:\\users\\khush\\anaconda3\\lib\\site-packages (from streamlit) (8.1.7)\n",
      "Requirement already satisfied: numpy<2,>=1.19.3 in c:\\users\\khush\\anaconda3\\lib\\site-packages (from streamlit) (1.26.4)\n",
      "Requirement already satisfied: packaging<24,>=16.8 in c:\\users\\khush\\anaconda3\\lib\\site-packages (from streamlit) (23.2)\n",
      "Requirement already satisfied: pandas<3,>=1.3.0 in c:\\users\\khush\\anaconda3\\lib\\site-packages (from streamlit) (2.2.2)\n",
      "Requirement already satisfied: pillow<11,>=7.1.0 in c:\\users\\khush\\anaconda3\\lib\\site-packages (from streamlit) (10.3.0)\n",
      "Requirement already satisfied: protobuf<5,>=3.20 in c:\\users\\khush\\anaconda3\\lib\\site-packages (from streamlit) (3.20.3)\n",
      "Requirement already satisfied: pyarrow>=7.0 in c:\\users\\khush\\anaconda3\\lib\\site-packages (from streamlit) (14.0.2)\n",
      "Requirement already satisfied: requests<3,>=2.27 in c:\\users\\khush\\appdata\\roaming\\python\\python312\\site-packages (from streamlit) (2.31.0)\n",
      "Requirement already satisfied: rich<14,>=10.14.0 in c:\\users\\khush\\anaconda3\\lib\\site-packages (from streamlit) (13.3.5)\n",
      "Requirement already satisfied: tenacity<9,>=8.1.0 in c:\\users\\khush\\anaconda3\\lib\\site-packages (from streamlit) (8.2.2)\n",
      "Requirement already satisfied: toml<2,>=0.10.1 in c:\\users\\khush\\anaconda3\\lib\\site-packages (from streamlit) (0.10.2)\n",
      "Requirement already satisfied: typing-extensions<5,>=4.3.0 in c:\\users\\khush\\anaconda3\\lib\\site-packages (from streamlit) (4.11.0)\n",
      "Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in c:\\users\\khush\\anaconda3\\lib\\site-packages (from streamlit) (3.1.37)\n",
      "Requirement already satisfied: pydeck<1,>=0.8.0b4 in c:\\users\\khush\\anaconda3\\lib\\site-packages (from streamlit) (0.8.0)\n",
      "Requirement already satisfied: tornado<7,>=6.0.3 in c:\\users\\khush\\appdata\\roaming\\python\\python312\\site-packages (from streamlit) (6.4.1)\n",
      "Requirement already satisfied: watchdog>=2.1.5 in c:\\users\\khush\\anaconda3\\lib\\site-packages (from streamlit) (4.0.1)\n",
      "Requirement already satisfied: jinja2 in c:\\users\\khush\\anaconda3\\lib\\site-packages (from altair<6,>=4.0->streamlit) (3.1.4)\n",
      "Requirement already satisfied: jsonschema>=3.0 in c:\\users\\khush\\anaconda3\\lib\\site-packages (from altair<6,>=4.0->streamlit) (4.19.2)\n",
      "Requirement already satisfied: toolz in c:\\users\\khush\\anaconda3\\lib\\site-packages (from altair<6,>=4.0->streamlit) (0.12.0)\n",
      "Requirement already satisfied: colorama in c:\\users\\khush\\appdata\\roaming\\python\\python312\\site-packages (from click<9,>=7.0->streamlit) (0.4.6)\n",
      "Requirement already satisfied: gitdb<5,>=4.0.1 in c:\\users\\khush\\anaconda3\\lib\\site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.7)\n",
      "Requirement already satisfied: python-dateutil>=2.8.2 in c:\\users\\khush\\appdata\\roaming\\python\\python312\\site-packages (from pandas<3,>=1.3.0->streamlit) (2.9.0.post0)\n",
      "Requirement already satisfied: pytz>=2020.1 in c:\\users\\khush\\anaconda3\\lib\\site-packages (from pandas<3,>=1.3.0->streamlit) (2024.1)\n",
      "Requirement already satisfied: tzdata>=2022.7 in c:\\users\\khush\\anaconda3\\lib\\site-packages (from pandas<3,>=1.3.0->streamlit) (2023.3)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in c:\\users\\khush\\appdata\\roaming\\python\\python312\\site-packages (from requests<3,>=2.27->streamlit) (3.3.2)\n",
      "Requirement already satisfied: idna<4,>=2.5 in c:\\users\\khush\\appdata\\roaming\\python\\python312\\site-packages (from requests<3,>=2.27->streamlit) (3.4)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in c:\\users\\khush\\appdata\\roaming\\python\\python312\\site-packages (from requests<3,>=2.27->streamlit) (2.1.0)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in c:\\users\\khush\\appdata\\roaming\\python\\python312\\site-packages (from requests<3,>=2.27->streamlit) (2023.11.17)\n",
      "Requirement already satisfied: markdown-it-py<3.0.0,>=2.2.0 in c:\\users\\khush\\anaconda3\\lib\\site-packages (from rich<14,>=10.14.0->streamlit) (2.2.0)\n",
      "Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\\users\\khush\\appdata\\roaming\\python\\python312\\site-packages (from rich<14,>=10.14.0->streamlit) (2.18.0)\n",
      "Requirement already satisfied: smmap<5,>=3.0.1 in c:\\users\\khush\\anaconda3\\lib\\site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.0)\n",
      "Requirement already satisfied: MarkupSafe>=2.0 in c:\\users\\khush\\anaconda3\\lib\\site-packages (from jinja2->altair<6,>=4.0->streamlit) (2.1.3)\n",
      "Requirement already satisfied: attrs>=22.2.0 in c:\\users\\khush\\anaconda3\\lib\\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (23.1.0)\n",
      "Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\\users\\khush\\anaconda3\\lib\\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (2023.7.1)\n",
      "Requirement already satisfied: referencing>=0.28.4 in c:\\users\\khush\\anaconda3\\lib\\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.30.2)\n",
      "Requirement already satisfied: rpds-py>=0.7.1 in c:\\users\\khush\\anaconda3\\lib\\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.10.6)\n",
      "Requirement already satisfied: mdurl~=0.1 in c:\\users\\khush\\anaconda3\\lib\\site-packages (from markdown-it-py<3.0.0,>=2.2.0->rich<14,>=10.14.0->streamlit) (0.1.0)\n",
      "Requirement already satisfied: six>=1.5 in c:\\users\\khush\\appdata\\roaming\\python\\python312\\site-packages (from python-dateutil>=2.8.2->pandas<3,>=1.3.0->streamlit) (1.16.0)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "DEPRECATION: Loading egg at c:\\users\\khush\\anaconda3\\lib\\site-packages\\huggingface_hub-0.29.2-py3.8.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330\n",
      "\n",
      "[notice] A new release of pip is available: 23.3.1 -> 25.0.1\n",
      "[notice] To update, run: python.exe -m pip install --upgrade pip\n"
     ]
    }
   ],
   "source": [
    "!pip install streamlit\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "f1c406a3-2e48-45e3-8f4a-e229537100b8",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: pip in c:\\users\\khush\\appdata\\roaming\\python\\python312\\site-packages (23.3.1)\n",
      "Collecting pip\n",
      "  Downloading pip-25.0.1-py3-none-any.whl.metadata (3.7 kB)\n",
      "Downloading pip-25.0.1-py3-none-any.whl (1.8 MB)\n",
      "   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--\n",
      "   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--\n",
      "   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--\n",
      "   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--\n",
      "   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--\n",
      "   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--\n",
      "   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--\n",
      "   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--\n",
      "   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--\n",
      "   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--\n",
      "   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--\n",
      "   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--\n",
      "    --------------------------------------- 0.0/1.8 MB 109.5 kB/s eta 0:00:17\n",
      "    --------------------------------------- 0.0/1.8 MB 122.9 kB/s eta 0:00:15\n",
      "   - -------------------------------------- 0.1/1.8 MB 196.9 kB/s eta 0:00:09\n",
      "   -- ------------------------------------- 0.1/1.8 MB 256.7 kB/s eta 0:00:07\n",
      "   -- ------------------------------------- 0.1/1.8 MB 302.7 kB/s eta 0:00:06\n",
      "   --- ------------------------------------ 0.2/1.8 MB 374.9 kB/s eta 0:00:05\n",
      "   ---- ----------------------------------- 0.2/1.8 MB 423.1 kB/s eta 0:00:04\n",
      "   ------ --------------------------------- 0.3/1.8 MB 501.4 kB/s eta 0:00:04\n",
      "   ------ --------------------------------- 0.3/1.8 MB 531.5 kB/s eta 0:00:03\n",
      "   -------- ------------------------------- 0.4/1.8 MB 606.2 kB/s eta 0:00:03\n",
      "   --------- ------------------------------ 0.5/1.8 MB 640.9 kB/s eta 0:00:03\n",
      "   ---------- ----------------------------- 0.5/1.8 MB 684.6 kB/s eta 0:00:02\n",
      "   ------------ --------------------------- 0.6/1.8 MB 722.8 kB/s eta 0:00:02\n",
      "   -------------- ------------------------- 0.6/1.8 MB 781.9 kB/s eta 0:00:02\n",
      "   --------------- ------------------------ 0.7/1.8 MB 822.5 kB/s eta 0:00:02\n",
      "   ----------------- ---------------------- 0.8/1.8 MB 892.9 kB/s eta 0:00:02\n",
      "   -------------------- ------------------- 0.9/1.8 MB 972.6 kB/s eta 0:00:01\n",
      "   ---------------------- ----------------- 1.0/1.8 MB 1.0 MB/s eta 0:00:01\n",
      "   ------------------------ --------------- 1.1/1.8 MB 1.1 MB/s eta 0:00:01\n",
      "   ---------------------------- ----------- 1.3/1.8 MB 1.2 MB/s eta 0:00:01\n",
      "   ------------------------------- -------- 1.4/1.8 MB 1.2 MB/s eta 0:00:01\n",
      "   ----------------------------------- ---- 1.6/1.8 MB 1.4 MB/s eta 0:00:01\n",
      "   -------------------------------------- - 1.8/1.8 MB 1.4 MB/s eta 0:00:01\n",
      "   ---------------------------------------  1.8/1.8 MB 1.4 MB/s eta 0:00:01\n",
      "   ---------------------------------------- 1.8/1.8 MB 1.4 MB/s eta 0:00:00\n",
      "Installing collected packages: pip\n",
      "  Attempting uninstall: pip\n",
      "    Found existing installation: pip 23.3.1\n",
      "    Uninstalling pip-23.3.1:\n",
      "      Successfully uninstalled pip-23.3.1\n",
      "  Rolling back uninstall of pip\n",
      "  Moving to c:\\users\\khush\\appdata\\roaming\\python\\python312\\scripts\\pip.exe\n",
      "   from C:\\Users\\khush\\AppData\\Local\\Temp\\pip-uninstall-6ytaob2f\\pip.exe\n",
      "  Moving to c:\\users\\khush\\appdata\\roaming\\python\\python312\\scripts\\pip3.12.exe\n",
      "   from C:\\Users\\khush\\AppData\\Local\\Temp\\pip-uninstall-6ytaob2f\\pip3.12.exe\n",
      "  Moving to c:\\users\\khush\\appdata\\roaming\\python\\python312\\scripts\\pip3.exe\n",
      "   from C:\\Users\\khush\\AppData\\Local\\Temp\\pip-uninstall-6ytaob2f\\pip3.exe\n",
      "  Moving to c:\\users\\khush\\appdata\\roaming\\python\\python312\\site-packages\\pip-23.3.1.dist-info\\\n",
      "   from C:\\Users\\khush\\AppData\\Roaming\\Python\\Python312\\site-packages\\~ip-23.3.1.dist-info\n",
      "  Moving to c:\\users\\khush\\appdata\\roaming\\python\\python312\\site-packages\\pip\\\n",
      "   from C:\\Users\\khush\\AppData\\Roaming\\Python\\Python312\\site-packages\\~ip\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "DEPRECATION: Loading egg at c:\\users\\khush\\anaconda3\\lib\\site-packages\\huggingface_hub-0.29.2-py3.8.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330\n",
      "ERROR: Exception:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\khush\\AppData\\Roaming\\Python\\Python312\\site-packages\\pip\\_internal\\cli\\base_command.py\", line 180, in exc_logging_wrapper\n",
      "    status = run_func(*args)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\khush\\AppData\\Roaming\\Python\\Python312\\site-packages\\pip\\_internal\\cli\\req_command.py\", line 245, in wrapper\n",
      "    return func(self, options, args)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\khush\\AppData\\Roaming\\Python\\Python312\\site-packages\\pip\\_internal\\commands\\install.py\", line 452, in run\n",
      "    installed = install_given_reqs(\n",
      "                ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\khush\\AppData\\Roaming\\Python\\Python312\\site-packages\\pip\\_internal\\req\\__init__.py\", line 72, in install_given_reqs\n",
      "    requirement.install(\n",
      "  File \"C:\\Users\\khush\\AppData\\Roaming\\Python\\Python312\\site-packages\\pip\\_internal\\req\\req_install.py\", line 847, in install\n",
      "    install_wheel(\n",
      "  File \"C:\\Users\\khush\\AppData\\Roaming\\Python\\Python312\\site-packages\\pip\\_internal\\operations\\install\\wheel.py\", line 731, in install_wheel\n",
      "    _install_wheel(\n",
      "  File \"C:\\Users\\khush\\AppData\\Roaming\\Python\\Python312\\site-packages\\pip\\_internal\\operations\\install\\wheel.py\", line 648, in _install_wheel\n",
      "    generated_console_scripts = maker.make_multiple(scripts_to_generate)\n",
      "                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\khush\\AppData\\Roaming\\Python\\Python312\\site-packages\\pip\\_vendor\\distlib\\scripts.py\", line 436, in make_multiple\n",
      "    filenames.extend(self.make(specification, options))\n",
      "                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\khush\\AppData\\Roaming\\Python\\Python312\\site-packages\\pip\\_internal\\operations\\install\\wheel.py\", line 429, in make\n",
      "    return super().make(specification, options)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\khush\\AppData\\Roaming\\Python\\Python312\\site-packages\\pip\\_vendor\\distlib\\scripts.py\", line 425, in make\n",
      "    self._make_script(entry, filenames, options=options)\n",
      "  File \"C:\\Users\\khush\\AppData\\Roaming\\Python\\Python312\\site-packages\\pip\\_vendor\\distlib\\scripts.py\", line 325, in _make_script\n",
      "    self._write_script(scriptnames, shebang, script, filenames, ext)\n",
      "  File \"C:\\Users\\khush\\AppData\\Roaming\\Python\\Python312\\site-packages\\pip\\_vendor\\distlib\\scripts.py\", line 249, in _write_script\n",
      "    launcher = self._get_launcher('t')\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\khush\\AppData\\Roaming\\Python\\Python312\\site-packages\\pip\\_vendor\\distlib\\scripts.py\", line 404, in _get_launcher\n",
      "    raise ValueError(msg)\n",
      "ValueError: Unable to find resource t64.exe in package pip._vendor.distlib\n",
      "\n",
      "[notice] A new release of pip is available: 23.3.1 -> 25.0.1\n",
      "[notice] To update, run: python.exe -m pip install --upgrade pip\n"
     ]
    }
   ],
   "source": [
    "!python -m pip install --upgrade pip\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "e62e9be6-7bfc-456a-8dad-38ed56a0b4f8",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: pip in c:\\users\\khush\\appdata\\roaming\\python\\python312\\site-packages (23.3.1)\n",
      "Collecting pip\n",
      "  Using cached pip-25.0.1-py3-none-any.whl.metadata (3.7 kB)\n",
      "Using cached pip-25.0.1-py3-none-any.whl (1.8 MB)\n",
      "Installing collected packages: pip\n",
      "  Attempting uninstall: pip\n",
      "    Found existing installation: pip 23.3.1\n",
      "    Uninstalling pip-23.3.1:\n",
      "      Successfully uninstalled pip-23.3.1\n",
      "  Rolling back uninstall of pip\n",
      "  Moving to c:\\users\\khush\\appdata\\roaming\\python\\python312\\scripts\\pip.exe\n",
      "   from C:\\Users\\khush\\AppData\\Local\\Temp\\pip-uninstall-go2ck4iw\\pip.exe\n",
      "  Moving to c:\\users\\khush\\appdata\\roaming\\python\\python312\\scripts\\pip3.12.exe\n",
      "   from C:\\Users\\khush\\AppData\\Local\\Temp\\pip-uninstall-go2ck4iw\\pip3.12.exe\n",
      "  Moving to c:\\users\\khush\\appdata\\roaming\\python\\python312\\scripts\\pip3.exe\n",
      "   from C:\\Users\\khush\\AppData\\Local\\Temp\\pip-uninstall-go2ck4iw\\pip3.exe\n",
      "  Moving to c:\\users\\khush\\appdata\\roaming\\python\\python312\\site-packages\\pip-23.3.1.dist-info\\\n",
      "   from C:\\Users\\khush\\AppData\\Roaming\\Python\\Python312\\site-packages\\~ip-23.3.1.dist-info\n",
      "  Moving to c:\\users\\khush\\appdata\\roaming\\python\\python312\\site-packages\\pip\\\n",
      "   from C:\\Users\\khush\\AppData\\Roaming\\Python\\Python312\\site-packages\\~ip\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "DEPRECATION: Loading egg at c:\\users\\khush\\anaconda3\\lib\\site-packages\\huggingface_hub-0.29.2-py3.8.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330\n",
      "ERROR: Exception:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\khush\\AppData\\Roaming\\Python\\Python312\\site-packages\\pip\\_internal\\cli\\base_command.py\", line 180, in exc_logging_wrapper\n",
      "    status = run_func(*args)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\khush\\AppData\\Roaming\\Python\\Python312\\site-packages\\pip\\_internal\\cli\\req_command.py\", line 245, in wrapper\n",
      "    return func(self, options, args)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\khush\\AppData\\Roaming\\Python\\Python312\\site-packages\\pip\\_internal\\commands\\install.py\", line 452, in run\n",
      "    installed = install_given_reqs(\n",
      "                ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\khush\\AppData\\Roaming\\Python\\Python312\\site-packages\\pip\\_internal\\req\\__init__.py\", line 72, in install_given_reqs\n",
      "    requirement.install(\n",
      "  File \"C:\\Users\\khush\\AppData\\Roaming\\Python\\Python312\\site-packages\\pip\\_internal\\req\\req_install.py\", line 847, in install\n",
      "    install_wheel(\n",
      "  File \"C:\\Users\\khush\\AppData\\Roaming\\Python\\Python312\\site-packages\\pip\\_internal\\operations\\install\\wheel.py\", line 731, in install_wheel\n",
      "    _install_wheel(\n",
      "  File \"C:\\Users\\khush\\AppData\\Roaming\\Python\\Python312\\site-packages\\pip\\_internal\\operations\\install\\wheel.py\", line 648, in _install_wheel\n",
      "    generated_console_scripts = maker.make_multiple(scripts_to_generate)\n",
      "                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\khush\\AppData\\Roaming\\Python\\Python312\\site-packages\\pip\\_vendor\\distlib\\scripts.py\", line 436, in make_multiple\n",
      "    filenames.extend(self.make(specification, options))\n",
      "                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\khush\\AppData\\Roaming\\Python\\Python312\\site-packages\\pip\\_internal\\operations\\install\\wheel.py\", line 429, in make\n",
      "    return super().make(specification, options)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\khush\\AppData\\Roaming\\Python\\Python312\\site-packages\\pip\\_vendor\\distlib\\scripts.py\", line 425, in make\n",
      "    self._make_script(entry, filenames, options=options)\n",
      "  File \"C:\\Users\\khush\\AppData\\Roaming\\Python\\Python312\\site-packages\\pip\\_vendor\\distlib\\scripts.py\", line 325, in _make_script\n",
      "    self._write_script(scriptnames, shebang, script, filenames, ext)\n",
      "  File \"C:\\Users\\khush\\AppData\\Roaming\\Python\\Python312\\site-packages\\pip\\_vendor\\distlib\\scripts.py\", line 249, in _write_script\n",
      "    launcher = self._get_launcher('t')\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\khush\\AppData\\Roaming\\Python\\Python312\\site-packages\\pip\\_vendor\\distlib\\scripts.py\", line 404, in _get_launcher\n",
      "    raise ValueError(msg)\n",
      "ValueError: Unable to find resource t64.exe in package pip._vendor.distlib\n",
      "\n",
      "[notice] A new release of pip is available: 23.3.1 -> 25.0.1\n",
      "[notice] To update, run: python.exe -m pip install --upgrade pip\n"
     ]
    }
   ],
   "source": [
    "!python -m pip install --upgrade pip\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "5a2e29b5-5560-40da-928e-ea328232ee75",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: huggingface_hub in c:\\users\\khush\\anaconda3\\lib\\site-packages\\huggingface_hub-0.29.2-py3.8.egg (0.29.2)\n",
      "Collecting huggingface_hub\n",
      "  Downloading huggingface_hub-0.30.2-py3-none-any.whl.metadata (13 kB)\n",
      "Requirement already satisfied: filelock in c:\\users\\khush\\anaconda3\\lib\\site-packages (from huggingface_hub) (3.13.1)\n",
      "Requirement already satisfied: fsspec>=2023.5.0 in c:\\users\\khush\\anaconda3\\lib\\site-packages (from huggingface_hub) (2024.3.1)\n",
      "Requirement already satisfied: packaging>=20.9 in c:\\users\\khush\\anaconda3\\lib\\site-packages (from huggingface_hub) (23.2)\n",
      "Requirement already satisfied: pyyaml>=5.1 in c:\\users\\khush\\anaconda3\\lib\\site-packages (from huggingface_hub) (6.0.1)\n",
      "Requirement already satisfied: requests in c:\\users\\khush\\appdata\\roaming\\python\\python312\\site-packages (from huggingface_hub) (2.31.0)\n",
      "Requirement already satisfied: tqdm>=4.42.1 in c:\\users\\khush\\anaconda3\\lib\\site-packages (from huggingface_hub) (4.66.4)\n",
      "Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\\users\\khush\\anaconda3\\lib\\site-packages (from huggingface_hub) (4.11.0)\n",
      "Requirement already satisfied: colorama in c:\\users\\khush\\appdata\\roaming\\python\\python312\\site-packages (from tqdm>=4.42.1->huggingface_hub) (0.4.6)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in c:\\users\\khush\\appdata\\roaming\\python\\python312\\site-packages (from requests->huggingface_hub) (3.3.2)\n",
      "Requirement already satisfied: idna<4,>=2.5 in c:\\users\\khush\\appdata\\roaming\\python\\python312\\site-packages (from requests->huggingface_hub) (3.4)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in c:\\users\\khush\\appdata\\roaming\\python\\python312\\site-packages (from requests->huggingface_hub) (2.1.0)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in c:\\users\\khush\\appdata\\roaming\\python\\python312\\site-packages (from requests->huggingface_hub) (2023.11.17)\n",
      "Downloading huggingface_hub-0.30.2-py3-none-any.whl (481 kB)\n",
      "   ---------------------------------------- 0.0/481.4 kB ? eta -:--:--\n",
      "    --------------------------------------- 10.2/481.4 kB ? eta -:--:--\n",
      "   --- ----------------------------------- 41.0/481.4 kB 487.6 kB/s eta 0:00:01\n",
      "   ---------- ----------------------------- 122.9/481.4 kB 1.2 MB/s eta 0:00:01\n",
      "   ---------------------------------- ----- 419.8/481.4 kB 2.9 MB/s eta 0:00:01\n",
      "   ---------------------------------------- 481.4/481.4 kB 2.5 MB/s eta 0:00:00\n",
      "Installing collected packages: huggingface_hub\n",
      "  Attempting uninstall: huggingface_hub\n",
      "    Found existing installation: huggingface_hub 0.29.2\n",
      "    Uninstalling huggingface_hub-0.29.2:\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "DEPRECATION: Loading egg at c:\\users\\khush\\anaconda3\\lib\\site-packages\\huggingface_hub-0.29.2-py3.8.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330\n",
      "ERROR: Could not install packages due to an OSError: [WinError 32] The process cannot access the file because it is being used by another process: 'c:\\\\users\\\\khush\\\\anaconda3\\\\lib\\\\site-packages\\\\huggingface_hub-0.29.2-py3.8.egg'\n",
      "Consider using the `--user` option or check the permissions.\n",
      "\n",
      "\n",
      "[notice] A new release of pip is available: 23.3.1 -> 25.0.1\n",
      "[notice] To update, run: python.exe -m pip install --upgrade pip\n"
     ]
    }
   ],
   "source": [
    "!pip install --upgrade huggingface_hub\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "id": "14811523-8069-4406-b542-abf8337b0173",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Found existing installation: pip 23.3.1\n",
      "Uninstalling pip-23.3.1:\n",
      "  Successfully uninstalled pip-23.3.1\n",
      "Looking in links: c:\\Users\\khush\\AppData\\Local\\Temp\\tmpe209h1rc\n",
      "Requirement already satisfied: pip in c:\\users\\khush\\anaconda3\\lib\\site-packages (24.0)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "DEPRECATION: Loading egg at c:\\users\\khush\\anaconda3\\lib\\site-packages\\huggingface_hub-0.29.2-py3.8.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330\n"
     ]
    }
   ],
   "source": [
    "# Uninstall pip\n",
    "!python -m pip uninstall -y pip\n",
    "\n",
    "# Reinstall pip using ensurepip\n",
    "!python -m ensurepip --upgrade\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "id": "992c9b5c-bbfb-47c0-a8a5-cc968a7df2c3",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Found existing installation: huggingface_hub 0.29.2\n",
      "Uninstalling huggingface_hub-0.29.2:\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "DEPRECATION: Loading egg at c:\\users\\khush\\anaconda3\\lib\\site-packages\\huggingface_hub-0.29.2-py3.8.egg is deprecated. pip 25.1 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330\n",
      "ERROR: Exception:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\khush\\anaconda3\\Lib\\shutil.py\", line 847, in move\n",
      "    os.rename(src, real_dst)\n",
      "PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'c:\\\\users\\\\khush\\\\anaconda3\\\\lib\\\\site-packages\\\\huggingface_hub-0.29.2-py3.8.egg' -> 'C:\\\\Users\\\\khush\\\\AppData\\\\Local\\\\Temp\\\\pip-uninstall-288v2fzp\\\\huggingface_hub-0.29.2-py3.8.egg'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\khush\\anaconda3\\Lib\\site-packages\\pip\\_internal\\cli\\base_command.py\", line 106, in _run_wrapper\n",
      "    status = _inner_run()\n",
      "             ^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\khush\\anaconda3\\Lib\\site-packages\\pip\\_internal\\cli\\base_command.py\", line 97, in _inner_run\n",
      "    return self.run(options, args)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\khush\\anaconda3\\Lib\\site-packages\\pip\\_internal\\commands\\uninstall.py\", line 106, in run\n",
      "    uninstall_pathset = req.uninstall(\n",
      "                        ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\khush\\anaconda3\\Lib\\site-packages\\pip\\_internal\\req\\req_install.py\", line 723, in uninstall\n",
      "    uninstalled_pathset.remove(auto_confirm, verbose)\n",
      "  File \"C:\\Users\\khush\\anaconda3\\Lib\\site-packages\\pip\\_internal\\req\\req_uninstall.py\", line 370, in remove\n",
      "    moved.stash(path)\n",
      "  File \"C:\\Users\\khush\\anaconda3\\Lib\\site-packages\\pip\\_internal\\req\\req_uninstall.py\", line 261, in stash\n",
      "    renames(path, new_path)\n",
      "  File \"C:\\Users\\khush\\anaconda3\\Lib\\site-packages\\pip\\_internal\\utils\\misc.py\", line 350, in renames\n",
      "    shutil.move(old, new)\n",
      "  File \"C:\\Users\\khush\\anaconda3\\Lib\\shutil.py\", line 868, in move\n",
      "    os.unlink(src)\n",
      "PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'c:\\\\users\\\\khush\\\\anaconda3\\\\lib\\\\site-packages\\\\huggingface_hub-0.29.2-py3.8.egg'\n"
     ]
    }
   ],
   "source": [
    "!pip uninstall -y huggingface_hub\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "id": "1a8cf469-2edd-4e33-b40e-847ee0bdb48f",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: huggingface_hub in c:\\users\\khush\\anaconda3\\lib\\site-packages\\huggingface_hub-0.29.2-py3.8.egg (0.29.2)\n",
      "Requirement already satisfied: filelock in c:\\users\\khush\\anaconda3\\lib\\site-packages (from huggingface_hub) (3.13.1)\n",
      "Requirement already satisfied: fsspec>=2023.5.0 in c:\\users\\khush\\anaconda3\\lib\\site-packages (from huggingface_hub) (2024.3.1)\n",
      "Requirement already satisfied: packaging>=20.9 in c:\\users\\khush\\anaconda3\\lib\\site-packages (from huggingface_hub) (23.2)\n",
      "Requirement already satisfied: pyyaml>=5.1 in c:\\users\\khush\\anaconda3\\lib\\site-packages (from huggingface_hub) (6.0.1)\n",
      "Requirement already satisfied: requests in c:\\users\\khush\\appdata\\roaming\\python\\python312\\site-packages (from huggingface_hub) (2.31.0)\n",
      "Requirement already satisfied: tqdm>=4.42.1 in c:\\users\\khush\\anaconda3\\lib\\site-packages (from huggingface_hub) (4.66.4)\n",
      "Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\\users\\khush\\anaconda3\\lib\\site-packages (from huggingface_hub) (4.11.0)\n",
      "Requirement already satisfied: colorama in c:\\users\\khush\\appdata\\roaming\\python\\python312\\site-packages (from tqdm>=4.42.1->huggingface_hub) (0.4.6)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in c:\\users\\khush\\appdata\\roaming\\python\\python312\\site-packages (from requests->huggingface_hub) (3.3.2)\n",
      "Requirement already satisfied: idna<4,>=2.5 in c:\\users\\khush\\appdata\\roaming\\python\\python312\\site-packages (from requests->huggingface_hub) (3.4)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in c:\\users\\khush\\appdata\\roaming\\python\\python312\\site-packages (from requests->huggingface_hub) (2.1.0)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in c:\\users\\khush\\appdata\\roaming\\python\\python312\\site-packages (from requests->huggingface_hub) (2023.11.17)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "DEPRECATION: Loading egg at c:\\users\\khush\\anaconda3\\lib\\site-packages\\huggingface_hub-0.29.2-py3.8.egg is deprecated. pip 25.1 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330\n"
     ]
    }
   ],
   "source": [
    "!pip install huggingface_hub\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "id": "727f9b7f-9f35-48b2-b271-41b0b05d0bc4",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Failed to remove: [WinError 267] The directory name is invalid: 'c:\\\\users\\\\khush\\\\anaconda3\\\\lib\\\\site-packages\\\\huggingface_hub-0.29.2-py3.8.egg'\n"
     ]
    }
   ],
   "source": [
    "import os\n",
    "import shutil\n",
    "\n",
    "egg_path = r\"c:\\users\\khush\\anaconda3\\lib\\site-packages\\huggingface_hub-0.29.2-py3.8.egg\"\n",
    "\n",
    "if os.path.exists(egg_path):\n",
    "    try:\n",
    "        shutil.rmtree(egg_path)\n",
    "        print(\"Old egg file removed successfully.\")\n",
    "    except Exception as e:\n",
    "        print(f\"Failed to remove: {e}\")\n",
    "else:\n",
    "    print(\"Egg file not found.\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "id": "4911008b-ef23-4f3a-b4c8-3f7d98908086",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Failed to remove: [WinError 267] The directory name is invalid: 'c:\\\\users\\\\khush\\\\anaconda3\\\\lib\\\\site-packages\\\\huggingface_hub-0.29.2-py3.8.egg'\n"
     ]
    }
   ],
   "source": [
    "import os\n",
    "import shutil\n",
    "\n",
    "egg_path = r\"c:\\users\\khush\\anaconda3\\lib\\site-packages\\huggingface_hub-0.29.2-py3.8.egg\"\n",
    "\n",
    "if os.path.exists(egg_path):\n",
    "    try:\n",
    "        shutil.rmtree(egg_path)\n",
    "        print(\"Old egg file removed successfully.\")\n",
    "    except Exception as e:\n",
    "        print(f\"Failed to remove: {e}\")\n",
    "else:\n",
    "    print(\"Egg file not found.\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 27,
   "id": "6489a3b4-e84c-49dc-a46a-64a477d02acc",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Failed to remove: [WinError 32] The process cannot access the file because it is being used by another process: 'c:\\\\users\\\\khush\\\\anaconda3\\\\lib\\\\site-packages\\\\huggingface_hub-0.29.2-py3.8.egg'\n"
     ]
    }
   ],
   "source": [
    "import os\n",
    "\n",
    "egg_path = r\"c:\\users\\khush\\anaconda3\\lib\\site-packages\\huggingface_hub-0.29.2-py3.8.egg\"\n",
    "\n",
    "if os.path.exists(egg_path):\n",
    "    try:\n",
    "        os.remove(egg_path)\n",
    "        print(\"Old egg file removed successfully.\")\n",
    "    except Exception as e:\n",
    "        print(f\"Failed to remove: {e}\")\n",
    "else:\n",
    "    print(\"Egg file not found.\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 29,
   "id": "49abed7f-d54d-4cae-a8df-0ff06f94c1cc",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: huggingface_hub in c:\\users\\khush\\anaconda3\\lib\\site-packages\\huggingface_hub-0.29.2-py3.8.egg (0.29.2)\n",
      "Requirement already satisfied: filelock in c:\\users\\khush\\anaconda3\\lib\\site-packages (from huggingface_hub) (3.13.1)\n",
      "Requirement already satisfied: fsspec>=2023.5.0 in c:\\users\\khush\\anaconda3\\lib\\site-packages (from huggingface_hub) (2024.3.1)\n",
      "Requirement already satisfied: packaging>=20.9 in c:\\users\\khush\\anaconda3\\lib\\site-packages (from huggingface_hub) (23.2)\n",
      "Requirement already satisfied: pyyaml>=5.1 in c:\\users\\khush\\anaconda3\\lib\\site-packages (from huggingface_hub) (6.0.1)\n",
      "Requirement already satisfied: requests in c:\\users\\khush\\appdata\\roaming\\python\\python312\\site-packages (from huggingface_hub) (2.31.0)\n",
      "Requirement already satisfied: tqdm>=4.42.1 in c:\\users\\khush\\anaconda3\\lib\\site-packages (from huggingface_hub) (4.66.4)\n",
      "Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\\users\\khush\\anaconda3\\lib\\site-packages (from huggingface_hub) (4.11.0)\n",
      "Requirement already satisfied: colorama in c:\\users\\khush\\appdata\\roaming\\python\\python312\\site-packages (from tqdm>=4.42.1->huggingface_hub) (0.4.6)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in c:\\users\\khush\\appdata\\roaming\\python\\python312\\site-packages (from requests->huggingface_hub) (3.3.2)\n",
      "Requirement already satisfied: idna<4,>=2.5 in c:\\users\\khush\\appdata\\roaming\\python\\python312\\site-packages (from requests->huggingface_hub) (3.4)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in c:\\users\\khush\\appdata\\roaming\\python\\python312\\site-packages (from requests->huggingface_hub) (2.1.0)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in c:\\users\\khush\\appdata\\roaming\\python\\python312\\site-packages (from requests->huggingface_hub) (2023.11.17)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "DEPRECATION: Loading egg at c:\\users\\khush\\anaconda3\\lib\\site-packages\\huggingface_hub-0.29.2-py3.8.egg is deprecated. pip 25.1 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330\n"
     ]
    }
   ],
   "source": [
    "!pip install huggingface_hub --no-cache-dir\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 31,
   "id": "fdd40576-fa62-45f3-a809-44dfe72409dc",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "❌ Could not delete file: [WinError 32] The process cannot access the file because it is being used by another process: 'c:\\\\users\\\\khush\\\\anaconda3\\\\lib\\\\site-packages\\\\huggingface_hub-0.29.2-py3.8.egg'\n"
     ]
    }
   ],
   "source": [
    "import os\n",
    "\n",
    "egg_path = r\"c:\\users\\khush\\anaconda3\\lib\\site-packages\\huggingface_hub-0.29.2-py3.8.egg\"\n",
    "\n",
    "try:\n",
    "    os.remove(egg_path)\n",
    "    print(\"✅ .egg file deleted successfully.\")\n",
    "except Exception as e:\n",
    "    print(f\"❌ Could not delete file: {e}\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 33,
   "id": "d39ffc7b-506b-4f47-a3c7-7f119861cc9e",
   "metadata": {},
   "outputs": [
    {
     "ename": "SyntaxError",
     "evalue": "invalid character '❌' (U+274C) (1193035753.py, line 1)",
     "output_type": "error",
     "traceback": [
      "\u001b[1;36m  Cell \u001b[1;32mIn[33], line 1\u001b[1;36m\u001b[0m\n\u001b[1;33m    ❌ Could not delete file: [WinError 32] The process cannot access the file because it is being used by another process: 'c:\\\\users\\\\khush\\\\anaconda3\\\\lib\\\\site-packages\\\\huggingface_hub-0.29.2-py3.8.egg'\u001b[0m\n\u001b[1;37m    ^\u001b[0m\n\u001b[1;31mSyntaxError\u001b[0m\u001b[1;31m:\u001b[0m invalid character '❌' (U+274C)\n"
     ]
    }
   ],
   "source": [
    "❌ Could not delete file: [WinError 32] The process cannot access the file because it is being used by another process: 'c:\\\\users\\\\khush\\\\anaconda3\\\\lib\\\\site-packages\\\\huggingface_hub-0.29.2-py3.8.egg'"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "671a3872-d79b-4d55-aa31-be01e04f18c1",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
